// <auto-generated />
using System;
using JB.Integration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JB.Integration.Data.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20191117161909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JB.Integration.Core.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d47b7038-4bee-4beb-90b5-8f424938c862"),
                            Created = new DateTime(2019, 11, 17, 17, 19, 9, 338, DateTimeKind.Local).AddTicks(6372),
                            Email = "johnnblade@hotmail.com",
                            LastUpdated = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(1146),
                            Password = "12345678",
                            UserName = "John Doe1"
                        },
                        new
                        {
                            UserId = new Guid("2641a7b5-d60e-4188-9cef-43231d37649f"),
                            Created = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2181),
                            Email = "johnnblade2@hotmail.com",
                            LastUpdated = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2219),
                            Password = "12345678",
                            UserName = "John Doe2"
                        },
                        new
                        {
                            UserId = new Guid("a1d76be3-29a7-4b0d-b967-9b60e07d098b"),
                            Created = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2247),
                            Email = "johnnblade3@hotmail.com",
                            LastUpdated = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2253),
                            Password = "12345678",
                            UserName = "John Doe3"
                        },
                        new
                        {
                            UserId = new Guid("412a7aea-8019-4849-9d0c-9bd339dc3d70"),
                            Created = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2261),
                            Email = "johnnblade4@hotmail.com",
                            LastUpdated = new DateTime(2019, 11, 17, 17, 19, 9, 342, DateTimeKind.Local).AddTicks(2266),
                            Password = "12345678",
                            UserName = "John Doe4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
